name: Manuelles SFTP Deployment

on:
  workflow_dispatch:  # Ermöglicht manuelle Auslösung über die GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.SFTPSERVERURL }}
        username: ${{ secrets.SFTPSERVERUSER }}
        password: ${{ secrets.SFTPSERVERPASSWORD }}
        port: 22
        local_path: './backendjobs/*'  # Alle Dateien im backendjobs Ordner
        remote_path: './'  # Da dein Benutzer bereits im richtigen Ordner landet
        sftp_only: true
        delete_remote_files: false
        excludes: 'db_connect.php'  # Diese Datei ausschließen
