name: Job Scraping and Processing Pipeline

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run job scraper
      run: python job_scraper.py

    - name: Upload scraped data
      uses: actions/upload-artifact@v3
      with:
        name: scraped-data
        path: |
          jobs_all_processed.json
          new_jobs.json

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add jobs_all_processed.json new_jobs.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update job data" && git push)

  process:
    needs: scrape
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Download scraped data
      uses: actions/download-artifact@v3
      with:
        name: scraped-data

    - name: Run job processor
      run: |
        python job_processor.py
        echo "RELEVANT_JOBS_FILE=$(python job_processor.py | grep 'Saved to' | cut -d ' ' -f 4)" >> $GITHUB_ENV

    - name: Upload processed data
      uses: actions/upload-artifact@v3
      with:
        name: processed-data
        path: ${{ env.RELEVANT_JOBS_FILE }}

    - name: Commit and push processed data
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add ${{ env.RELEVANT_JOBS_FILE }}
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update processed job data" && git push)

  notify:
    needs: process
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Download processed data
      uses: actions/download-artifact@v3
      with:
        name: processed-data

    - name: Send Telegram Notification
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python telegram_notifier.py

    - name: Commit and push relevant jobs
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add relevant_jobs/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update relevant jobs data" && git push)